services:
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: catalog
    ports:
      - "8000:8000" 
    environment:
      - DATABASE_URL=postgresql://library_9eon_user:n7oNCRTauRQABgKkMoyeeAI9S2XgxDop@dpg-cr9dv9bv2p9s73b641j0-a.oregon-postgres.render.com/library_9eon

  inventory_management:
    image: inventory
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://library_9eon_user:n7oNCRTauRQABgKkMoyeeAI9S2XgxDop@dpg-cr9dv9bv2p9s73b641j0-a.oregon-postgres.render.com/library_9eon